name = "quid-pr-quo"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Enable observability
[observability]
enabled = true

[durable_objects]
bindings = [
  { name = "ESCROW", class_name = "EscrowBox" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["EscrowBox"]

# Secrets to set via: wrangler secret put <NAME>
# GITHUB_APP_PRIVATE_KEY - GitHub App private key (PEM format)
# GITHUB_WEBHOOK_SECRET - GitHub App webhook secret (for HMAC verification) 
# GITHUB_CLIENT_SECRET - GitHub App client secret (for OAuth)
# GITHUB_APP_ID - GitHub App ID number
